# Generated by Django 4.2.18 on 2025-03-01 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies_db',
            name='year',
            field=models.IntegerField(),
        ),
    ]
